<?php /**
 * @var \Magento\Framework\View\Element\Template $this
 **/ ?>

<div class="footer-column footer-column-links">
    <h3>KLANTENSERVICE</h3>
    <ul class="footer-links">
        <li>
            <a href="<?= $this->getBaseUrl() ?>faq">F.A.Q.</a>
        </li>
        <li>
            <a href="<?= $this->getBaseUrl() ?>verzenden-en-retour">Verzenden & retour</a>
        </li>
        <li>
            <a href="<?= $this->getBaseUrl() ?>garantie">Garantie</a>
        </li>
    </ul>
</div>