<?php /**
 * @var \Magento\Framework\View\Element\Template $this
 **/ ?>

<div class="footer-column footer-column-links">
    <h3>VOLG ONS</h3>

    <p>
        <a href="https://www.facebook.com/hobbymolen"><i class="fa fa-icon fa-facebook"></i> Facebook</a>
    </p>
    <p>
        <a href="https://www.pinterest.com/hobbymolen/"><i class="fa fa-icon fa-pinterest"></i> Pinterest</a>
    </p>
</div>