<?php /**
 * @var \Magento\Framework\View\Element\Template $this
 **/?>

<div class="footer-column">
  <div class="footer-logo-wrapper">
    <img src="<?php echo $this->getViewFileUrl('images/logo_simple.svg'); ?>" class="footer-logo"/>
  </div>

  <p class="hobbymolen-description">
      Tien jaar geleden is de hobbymolen gestart als winkel voor hobby materialen.
      Nu tien jaar later zijn we gestart met een webshop waar u terecht kunt voor al uw creatieve vaardigheden.
  </p>
</div>