<?php /**
 * @var \Magento\Framework\View\Element\Template $this
 **/?>

<div class="footer-column">
  <div class="footer-logo-wrapper">
    <img src="<?php echo $this->getViewFileUrl('images/logo_simple.svg'); ?>" class="footer-logo"/>
  </div>

  <p class="hobbymolen-description">
      In 2000 is de Hobbymolen gestart met workshops in diverse creatieve technieken.
      De winkel opende in 2005 en sloot haar deuren Decemer 2016.
      Nu 1 jaar later zijn we gestart met een webshop waar u terecht kunt voor al uw creatieve vaardigheden.
  </p>
</div>