<?php /**
 * @var \Magento\Framework\View\Element\Template $this
 **/ ?>

<div class="footer-column footer-column-links">
    <h3>DE HOBBYMOLEN</h3>
    <ul class="footer-links">
        <li>
            <a href="<?= $this->getBaseUrl() ?>contact">Contact</a>
        </li>
        <li>
            <a href="<?= $this->getBaseUrl() ?>over-ons">Over ons</a>
        </li>
        <li>
            <a href="<?= $this->getBaseUrl() ?>algemene-voorwaarden">Algemene Voorwaarden</a>
        </li>
        <li>
            <a href="<?= $this->getBaseUrl() ?>privacy-policy">Privacy policy</a>
        </li>
    </ul>
</div>