<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Category layered navigation
 *
 * @var $block \Magento\LayeredNavigation\Block\Navigation
 */
?>

<?php if ($block->canShowBlock()): ?>
    <div class="block filter">
        <div class="block-content filter-content">
            <?php echo $block->getChildHtml('state') ?>
            <?php if ($block->getLayer()->getState()->getFilters()): ?>
            <?php endif; ?>
            <?php foreach ($block->getFilters() as $filter): ?>
                    <?php if ($filter->getItemsCount()): ?>
                    <img src="<?php echo $this->getViewFileUrl('images/borders/divider_small.svg'); ?>">
                        <dt role="heading" aria-level="3" class="filter-options-title"><?php echo $block->escapeHtml(__($filter->getName())) ?></dt>
                        <dd class="filter-options-content"><?php /* @escapeNotVerified */ echo $block->getChildBlock('renderer')->render($filter); ?></dd>
                    <?php endif; ?>
            <?php endforeach; ?>
        </div>
    </div>
<?php endif; ?>
