<div class="container-fluid">
    <div class="row">
        <div class="col-xs-12">
            <img class="home-banner" src="<?php echo $this->getViewFileUrl('images/placeholder/chips.jpg'); ?>" width="100%">
        </div>
    </div>
</div>
<div class="container">
    <div class="shop-now">
        <button>Shop nu!</button>
    </div>
</div>

<script>
require(['jquery'], function ($) {
    $(document).on('click', '.shop-now', function(e){
        $('html, body').animate({
            scrollTop: $('#category-list').offset().top
        }, 500);
    });
});
</script>