<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/** @var $block \Magento\Wishlist\Block\Catalog\Product\View\Addto\Wishlist */
?>
<?php if ($block->isWishListAllowed()) : ?>
    <a href="#"
       class="action towishlist"
       title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
       aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
       data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($block->getProduct()); ?>'
       data-action="add-to-wishlist"
       role="button">
        <?php $InWishlist =
//          !empty($block->getWishlistHelper()->getWishlistItemCollection()->addFieldToFilter('product_id', $block->getProduct()->getId())->getData());
        false;
        if(!$InWishlist):?>
            <img src="<?php echo $this->getViewFileUrl('images/icons/wishlist_icon.svg'); ?>">
        <?php else:?>
            <img src="<?php echo $this->getViewFileUrl('images/icons/wishlist_icon_active.svg'); ?>">
        <?php endif;?>
    </a>
<?php endif; ?>
