<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var $block \Magento\Catalog\Block\Product\AbstractProduct */
?>

<?php
switch ($type = $block->getType()) {

  case 'related-rule':
    if ($exist = $block->hasItems()) {
      $type  = 'related';
      $class = $type;

      $image             = 'related_products_list';
      $title             = __('Related Products');
      $items             = $block->getAllItems();
      $limit             = $block->getPositionLimit();
      $shuffle           = (int)$block->isShuffled();
      $canItemsAddToCart = $block->canItemsAddToCart();

      $showAddTo    = true;
      $showCart     = false;
      $templateType = null;
      $description  = false;
    }
    break;

  case 'related':
    /** @var \Magento\Catalog\Block\Product\ProductList\Related $block */
    if ($exist = $block->getItems()->getSize()) {
      $type  = 'related';
      $class = $type;

      $image             = 'related_products_list';
      $title             = __('Related Products');
      $items             = $block->getItems();
      $limit             = 0;
      $shuffle           = 0;
      $canItemsAddToCart = $block->canItemsAddToCart();

      $showAddTo    = true;
      $showCart     = false;
      $templateType = null;
      $description  = false;
    }
    break;

  case 'upsell-rule':
    if ($exist = $block->hasItems()) {
      $type  = 'upsell';
      $class = $type;

      $image   = 'upsell_products_list';
      $title   = __('We found other products you might like!');
      $items   = $block->getAllItems();
      $limit   = $block->getPositionLimit();
      $shuffle = (int)$block->isShuffled();

      $showAddTo         = false;
      $showCart          = false;
      $templateType      = null;
      $description       = false;
      $canItemsAddToCart = false;
    }
    break;

  case 'upsell':
    /** @var \Magento\Catalog\Block\Product\ProductList\Upsell $block */
    if ($exist = count($block->getItemCollection()->getItems())) {
      $type  = 'upsell';
      $class = $type;

      $image   = 'upsell_products_list';
      $title   = __('We found other products you might like!');
      $items   = $block->getItemCollection()->getItems();
      $limit   = $block->getItemLimit('upsell');
      $shuffle = 0;

      $showAddTo         = false;
      $showCart          = false;
      $templateType      = null;
      $description       = false;
      $canItemsAddToCart = false;
    }
    break;

  case 'crosssell-rule':
    /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
    if ($exist = $block->hasItems()) {
      $type  = 'crosssell';
      $class = $type;

      $image = 'cart_cross_sell_products';
      $title = __('More Choices:');
      $items = $block->getItemCollection();

      $showAddTo         = true;
      $showCart          = true;
      $templateType      = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
      $description       = false;
      $canItemsAddToCart = false;
    }
    break;

  case 'crosssell':
    /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
    if ($exist = $block->getItemCount()) {
      $type  = 'crosssell';
      $class = $type;

      $image = 'cart_cross_sell_products';
      $title = __('More Choices:');
      $items = $block->getItems();

      $showAddTo         = true;
      $showCart          = true;
      $templateType      = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
      $description       = false;
      $canItemsAddToCart = false;
    }
    break;

  case 'new':
    if ($exist = $block->getProductCollection()) {
      $type = 'new';
      $mode = 'grid';
      $type = $type . ' ' . $mode;

      $class = 'widget' . ' ' . $type;

      $image = 'new_products_content_widget_grid';
      $title = __('New Products');
      $items = $exist;

      $showAddTo         = true;
      $showCart          = true;
      $templateType      = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
      $description       = ($mode == 'list') ? true : false;
      $canItemsAddToCart = false;
    }
    break;

  case 'other':
    break;
}
$_helper            = $this->helper('Magento\Catalog\Helper\Output');
?>

<?php if ($exist): ?>

<?php if ($type == 'related' || $type == 'upsell'): ?>
<?php if ($type == 'related'): ?>
<div class="block <?php /* @escapeNotVerified */
echo $class; ?>" data-mage-init='{"relatedProducts":{"relatedCheckbox":".related.checkbox"}}'
     data-limit="<?php /* @escapeNotVerified */
     echo $limit; ?>" data-shuffle="<?php /* @escapeNotVerified */
echo $shuffle; ?>">
  <?php else: ?>
    <div class="block <?php /* @escapeNotVerified */
    echo $class; ?>" data-mage-init='{"upsellProducts":{}}' data-limit="<?php /* @escapeNotVerified */
    echo $limit; ?>" data-shuffle="<?php /* @escapeNotVerified */
    echo $shuffle; ?>">
      <?php endif; ?>
      <?php else: ?>
        <div class="block <?php /* @escapeNotVerified */
        echo $class; ?>">
          <?php endif; ?>
            <div class="block-title title">
                <h2 class="heading-border" role="heading" aria-level="2"><?=$title?></h2>
            </div>
            <div class="block-content content" aria-labelledby="block-<?php /* @escapeNotVerified */
            echo $class ?>-heading">
                <div class="products wrapper grid products-grid products-<?php /* @escapeNotVerified */
                echo $type; ?>">
                    <div class="row products list items product-items">
                      <?php $iterator = 1; ?>
                      <?php foreach ($items as $_item): ?>
                        <?php $available = ''; ?>
                        <?php if (!$_item->isComposite() && $_item->isSaleable() && $type == 'related'): ?>
                          <?php if (!$_item->getRequiredOptions()): ?>
                            <?php $available = 'related-available'; ?>
                          <?php endif; ?>
                        <?php endif; ?>
                          <div class="col-xs-6 col-md-4 col-lg-3 item product product-item"<?= ($type == 'related' || $type == 'upsell') ? 'style="display:none"' : '' ?>>
                              <div class="product-item-info <?php /* @escapeNotVerified */
                              echo $available; ?>">
                                <?php /* @escapeNotVerified */
                                echo '<!-- ' . $image . '-->' ?>
                                  <a href="<?php /* @escapeNotVerified */echo $block->getProductUrl($_item) ?>"
                                     class="product photo product-item-photo"
                                     target="_blank"
                                  >
                                    <?php echo $block->getImage($_item, $image)->toHtml(); ?>
                                  </a>
                                  <div class="product details product-item-details">
                                      <div class="product-info">
                                          <strong class="product name product-item-name">
                                              <a class="product-item-link"
                                                 title="<?php echo $block->escapeHtml($_item->getName()) ?>"
                                                 href="<?php /* @escapeNotVerified */echo $block->getProductUrl($_item) ?>"
                                                 target="_blank"
                                              >
                                              <?php echo $block->escapeHtml($_item->getName()) ?></a>
                                          </strong>

                                        <?php /* @escapeNotVerified */
                                        echo $block->getProductPrice($_item); ?>

                                        <?php if ($templateType): ?>
                                          <?php echo $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                        <?php endif; ?>

                                      </div>
                                      <div class="product-item-inner clearfix">
                                          <div class="product actions product-item-actions">
                                              <div class="actions-primary">
                                                <?php
                                                $postParams = $block->getAddToCartPostParams($_item);
                                                $disabled   = !$_item->isSaleable() || !$_item->getIsSalable();
                                                ?>
                                                  <form data-role="tocart-form" action="<?php /* @escapeNotVerified */
                                                  echo $postParams['action']; ?>" method="post">
                                                      <input type="hidden" name="product" value="<?php /* @escapeNotVerified */
                                                      echo $postParams['data']['product']; ?>">
                                                      <div class="field qty">
                                                          <div
                                                                  class="qty-min qty-control"
                                                                  <?php if ($disabled): ?>disabled<?php endif;
                                                          ?>
                                                          >
                                                            <?php if (!$disabled): ?>
                                                                <img src="<?php echo $this->getViewFileUrl('images/icons/min_icon.svg'); ?>">
                                                            <?php else: ?>
                                                                <img src="<?php echo $this->getViewFileUrl('images/icons/min_icon_disabled.svg'); ?>">
                                                            <?php endif; ?>
                                                          </div>
                                                          <div class="control qty-control">
                                                              <input type="number"
                                                                     name="qty"
                                                                     id="qty"
                                                                     maxlength="12"
                                                                     value="<?php /* @escapeNotVerified */
                                                                     echo max(1, $block->getProductDefaultQty() * 1) ?>"
                                                                     title="<?php /* @escapeNotVerified */
                                                                     echo __('Qty') ?>" class="input-text qty"
                                                                     data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                                                                     <?php if ($disabled): ?>disabled<?php endif;
                                                              ?>
                                                              />
                                                          </div>
                                                          <div
                                                                  class="qty-plus qty-control"
                                                                  <?php if($disabled):?>disabled<?php endif;?>
                                                          >
                                                            <?php if (!$disabled): ?>
                                                                <img src="<?php echo $this->getViewFileUrl('images/icons/plus_icon.svg'); ?>">
                                                            <?php else: ?>
                                                                <img src="<?php echo $this->getViewFileUrl('images/icons/plus_icon_disabled.svg'); ?>">
                                                            <?php endif; ?>
                                                          </div>
                                                      </div>
                                                      <div data-role="add-to-links"
                                                           class="add-to-links">
                                                        <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                                          <?php echo $addToBlock->setProduct($_item)->getChildHtml(); ?>
                                                        <?php endif; ?>
                                                      </div>
                                                    <?php echo $block->getBlockHtml('formkey') ?>
                                                      <button type="submit"
                                                              title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                              class="action tocart primary"
                                                              <?php if ($disabled): ?>disabled<?php endif;
                                                      ?>
                                                      >
                                          <span><?php /* @escapeNotVerified */
                                            echo __('Add to Cart') ?></span>
                                                      </button>
                                                  </form>
                                              </div>
                                          </div>

                                      </div>
                                  </div>
                              </div>
                          </div>
                      <?php endforeach ?>
                    </div>
                </div>
            </div>
        </div>
      <?php endif; ?>
