<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Top menu for store
 *
 * @var $block \Magento\Theme\Block\Html\Topmenu
 */
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$lBaseUrl = $storeManager->getStore()->getBaseUrl();

$columnsLimit = $block->getColumnsLimit() ?: 0;
$_menu = $block->getHtml('level-top', 'submenu', $columnsLimit) ?>

<nav class="navigation" data-action="navigation">
    <img src="<?php echo $this->getViewFileUrl('images/borders/border-1.svg'); ?>" class="navigation-border" alt="Navigation top border" />
    <ul data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
        <li class="level0 level-top">
            <a class="level-top" href="<?php echo $lBaseUrl; ?>">
                Home
            </a>
        </li>
      <?php /* @escapeNotVerified */ echo $_menu; ?>
        <li class="level0 level-top">
            <a class="level-top" href="<?php echo $lBaseUrl ?>/contact">
                Contact
            </a>
        </li>
      <?php /* @escapeNotVerified */ echo $block->getChildHtml(); ?>
    </ul>
    <img src="<?php echo $this->getViewFileUrl('images/borders/border-1.svg'); ?>" class="navigation-border" alt="Navigation bottom border"/>
</nav>
