<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Top menu for store
 *
 * @var $block \Magento\Theme\Block\Html\Topmenu
 */
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$lBaseUrl = $storeManager->getStore()->getBaseUrl();

$columnsLimit = $block->getColumnsLimit() ?: 0;
$_menu = $block->getHtml('level-top', 'submenu', $columnsLimit) ?>

<nav class="navigation" data-action="navigation">
    <img src="<?php echo $this->getViewFileUrl('images/borders/border-1.svg'); ?>" class="navigation-border" alt="Navigation top border" />
    <ul>
<!--    <ul data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>-->
        <li class="level0 level-top">
            <a class="level-top" href="<?php echo $lBaseUrl; ?>">
                Home
            </a>
        </li>
      <?php /* @escapeNotVerified */ echo $_menu; ?>
        <li class="level0 level-top">
            <a class="level-top" href="<?php echo $lBaseUrl ?>/contact">
                Contact
            </a>
        </li>
      <?php /* @escapeNotVerified */ echo $block->getChildHtml(); ?>
    </ul>
    <img src="<?php echo $this->getViewFileUrl('images/borders/border-1.svg'); ?>" class="navigation-border" alt="Navigation bottom border"/>
</nav>

<script>
    require(['jquery'], function ($) {
        $(document).find('.nav-sections li.parent:not(.open) a').on('touchstart', function(e){
            if($( window ).width() > 768) {
                e.preventDefault();
                e.stopPropagation();
                var li = $(this).closest('li');
                if(li.hasClass('level0')){
                    $(document).find('.nav-sections li').removeClass('open');
                }
                if(li.hasClass('level1')){
                    $(document).find('.nav-sections li.level1').removeClass('open');
                }
                li.addClass('open');
                return false;
            }
        });
        $(document).on('touchstart', ':not(.nav-sections *)', function(){
            if($( window ).width() > 768) {
                $(document).find('.nav-sections li.open').removeClass('open');
            }
        });
        $(document).on('click', '.nav-toggle', function(){
            $(document).find('.nav-sections').first().toggleClass('active');
        });
        $(document).on('click', '.nav-sections.active li > span', function(e){
            e.preventDefault();
            $(this).closest('li').toggleClass('open');
            return false;
        });
    });
</script>