<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper            = $this->helper('Magento\Catalog\Helper\Output');
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty">
        <div><?php /* @escapeNotVerified */
          echo __('We can\'t find products matching the selection.') ?></div>
    </div>
<?php else: ?>
  <?php echo $block->getToolbarHtml() ?>
  <?php echo $block->getAdditionalHtml() ?>
  <?php
  if ($block->getMode() == 'grid') {
    $viewMode        = 'grid';
    $image           = 'category_page_grid';
    $showDescription = false;
    $templateType    = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
  } else {
    $viewMode        = 'list';
    $image           = 'category_page_list';
    $showDescription = true;
    $templateType    = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
  }
  /**
   * Position for actions regarding image size changing in vde if needed
   */
  $pos = $block->getPositioned();
  ?>
    <div class="products wrapper <?php /* @escapeNotVerified */echo $viewMode; ?> products-<?php /* @escapeNotVerified */echo $viewMode; ?>">
      <?php $iterator = 1; ?>
        <div class="products list items product-items row">
          <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
          <?php foreach ($_productCollection as $_product):
            $lListItemClass = 'col-xs-6 col-md-4 item product product-item'; ?>
            <?php /* @escapeNotVerified */
            echo ($iterator++ == 1) ? '<div class="' . $lListItemClass . '">' : '</div><div class="' . $lListItemClass . '">' ?>
              <div class="product-item-info" data-container="product-grid">
                <?php
                $productImage = $block->getImage($_product, $image, ['width' => 324, 'height' => 324]);
                if ($pos != null) {
                  $position = ' style="left:' . $productImage->getWidth() . 'px;'
                    . 'top:' . $productImage->getHeight() . 'px;"';
                }
                ?>
                <?php // Product Image
                ?>

                  <a href="<?php /* @escapeNotVerified */
                  echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                    <?php echo $productImage->toHtml(); ?>
                  </a>
                  <div class="product details product-item-details">
                      <div class="product-info">
                        <?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
                          <strong class="product name product-item-name">
                              <a class="product-item-link"
                                 href="<?php /* @escapeNotVerified */
                                 echo $_product->getProductUrl() ?>">
                                <?php /* @escapeNotVerified */
                                echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                              </a>
                          </strong>
                        <?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
                          <?php
                          $msrpInclAttribute = $_product->getResource()->getAttribute('msrp_incl');
                          if ($msrpInclAttribute) {
                            $msrpInclAttribute = floatval($msrpInclAttribute->getFrontend()->getValue($_product));
                            if ($msrpInclAttribute) {
                              ?>
                                <div class="msrp">Advies prijs <span
                                            class="msrp-price">€ <?= number_format($msrpInclAttribute, 2) ?></span>
                                </div>
                              <?php
                            }
                          }?>
                          <?php /* @escapeNotVerified */
                        echo $block->getProductPrice($_product) ?>
                        <?php echo $block->getProductDetailsHtml($_product); ?>
                      </div>
                      <div class="product-item-inner clearfix">
                          <div class="product actions product-item-actions"<?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
                              <div class="actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
                                <?php
                                $postParams = $block->getAddToCartPostParams($_product);
                                $disabled   = !$_product->isSaleable() || !$_product->getIsSalable();
                                ?>
                                  <form data-role="tocart-form" action="<?php /* @escapeNotVerified */
                                  echo $postParams['action']; ?>" method="post">
                                      <input type="hidden" name="product" value="<?php /* @escapeNotVerified */
                                      echo $postParams['data']['product']; ?>">
                                      <input type="hidden" name="<?php /* @escapeNotVerified */
                                      echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */
                                      echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                      <div class="field qty">
                                          <div
                                              class="qty-min qty-control"
                                              <?php if ($disabled): ?>disabled<?php endif;
                                          ?>
                                          >
                                            <?php if (!$disabled): ?>
                                                <img src="<?php echo $this->getViewFileUrl('images/icons/min_icon.svg'); ?>">
                                            <?php else: ?>
                                                <img src="<?php echo $this->getViewFileUrl('images/icons/min_icon_disabled.svg'); ?>">
                                            <?php endif; ?>
                                          </div>
                                          <div class="control qty-control">
                                              <input type="number"
                                                     name="qty"
                                                     id="qty"
                                                     maxlength="12"
                                                     value="<?php /* @escapeNotVerified */
                                                     echo max(1, $block->getProductDefaultQty() * 1) ?>"
                                                     title="<?php /* @escapeNotVerified */
                                                     echo __('Qty') ?>" class="input-text qty"
                                                     data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                                                     <?php if ($disabled): ?>disabled<?php endif;
                                              ?>
                                              />
                                          </div>
                                          <div
                                                  class="qty-plus qty-control"
                                                  <?php if($disabled):?>disabled<?php endif;?>
                                          >
                                            <?php if (!$disabled): ?>
                                                <img src="<?php echo $this->getViewFileUrl('images/icons/plus_icon.svg'); ?>">
                                            <?php else: ?>
                                                <img src="<?php echo $this->getViewFileUrl('images/icons/plus_icon_disabled.svg'); ?>">
                                            <?php endif; ?>
                                          </div>
                                      </div>
                                      <div data-role="add-to-links"
                                           class="add-to-links"<?php echo strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>
                                        <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                          <?php echo $addToBlock->setProduct($_product)->getChildHtml(); ?>
                                        <?php endif; ?>
                                      </div>
                                    <?php echo $block->getBlockHtml('formkey') ?>
                                      <button type="submit"
                                              title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                              class="action tocart primary"
                                              <?php if ($disabled): ?>disabled<?php endif;
                                      ?>
                                      >
                                          <span><?php /* @escapeNotVerified */
                                            echo __('Add to Cart') ?></span>
                                      </button>
                                  </form>
                              </div>
                          </div>
                        <?php if ($showDescription): ?>
                            <div class="product description product-item-description">
                              <?php /* @escapeNotVerified */
                              echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                <a href="<?php /* @escapeNotVerified */
                                echo $_product->getProductUrl() ?>" title="<?php /* @escapeNotVerified */
                                echo $_productNameStripped ?>"
                                   class="action more"><?php /* @escapeNotVerified */
                                  echo __('Learn More') ?></a>
                            </div>
                        <?php endif; ?>
                      </div>
                  </div>
              </div>
            <?php echo ($iterator == count($_productCollection) + 1) ? '</div>' : '' ?>
          <?php endforeach; ?>
        </div>
    </div>

  <?php echo $block->getToolbarHtml() ?>
  <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }

        </script>
  <?php endif; ?>
    <script>
        require(['jquery', 'jquery.matchHeight'], function ($) {
            $(document).find('.product-item').matchHeight();
        });

        require(['jquery', 'jquery/ui'], function ($) {
            $(document).on('click touch', '.qty-min:not([disabled])', function () {
                var input = $(this).parent().find('input').first();
                input.val(parseInt(input.val()) - 1)
            });
            $(document).on('click touch', '.qty-plus:not([disabled])', function () {
                var input = $(this).parent().find('input').first();
                input.val(parseInt(input.val()) + 1)
            });
        });
    </script>
<?php endif; ?>
